<a href="https://colab.research.google.com/github/JoseSergio414/Projeto-Integrador-II/blob/main/PROJETOII_dados_finais_impfinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cadeia Automotiva dados finais importação

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
origem = '/content/drive/MyDrive/Data/COMEXSTAT/'

In [ ]:
arquivo_1 = origem + 'dado_imp_final1.csv'

In [ ]:
impfinal = pd.read_csv(arquivo_1,low_memory=False,sep=',',encoding='UTF-8')

In [ ]:
impfinal = impfinal.rename(columns={'VL_FOB': 'TOTAL IMPORTADO'})

In [ ]:
impfinal = impfinal.rename(columns={'KG_LIQUIDO': 'TOTAL KGL IMP.'})

In [ ]:
impfinal.head(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,TOTAL KGL IMP.,TOTAL IMPORTADO,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
0,2021,7,23,SP,3416200,3668,11688,4115,Couro reconstituído à base de couro ou de fibr...,Franca,Alemanha
1,2021,4,160,SP,3424709,1,3685,8525,Aparelhos emissores (transmissores) para radio...,Jaguariúna,China
2,2021,7,160,SP,3409205,5043,45918,8302,"Guarnições, ferragens e artigos semelhantes, d...",Cajamar,China
3,2021,1,249,SP,3420509,10417,207124,4009,"Tubos de borracha vulcanizada não endurecida, ...",Indaiatuba,Estados Unidos
4,2021,11,160,SP,3450308,306224,3298907,8536,"Aparelhos para interrupção, seccionamento, pro...",São Paulo,China

In [ ]:
impfinal.head()

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,TOTAL KGL IMP.,TOTAL IMPORTADO,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
0,2021,7,23,SP,3416200,3668,11688,4115,Couro reconstituído à base de couro ou de fibr...,Franca,Alemanha
1,2021,4,160,SP,3424709,1,3685,8525,Aparelhos emissores (transmissores) para radio...,Jaguariúna,China
2,2021,7,160,SP,3409205,5043,45918,8302,"Guarnições, ferragens e artigos semelhantes, d...",Cajamar,China
3,2021,1,249,SP,3420509,10417,207124,4009,"Tubos de borracha vulcanizada não endurecida, ...",Indaiatuba,Estados Unidos
4,2021,11,160,SP,3450308,306224,3298907,8536,"Aparelhos para interrupção, seccionamento, pro...",São Paulo,China

In [ ]:
impfinal.tail(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,TOTAL KGL IMP.,TOTAL IMPORTADO,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
8581655,2026,2,351,SC,4208906,1412,202140,8537,"Quadros, painéis, consolas, cabinas, armários ...",Jaraguá do Sul,Hong Kong
8581656,2026,2,72,GO,5303203,0,217,8536,"Aparelhos para interrupção, seccionamento, pro...",Barro Alto,Áustria
8581657,2026,2,603,BA,2905701,3,1143,8544,"Fios, cabos (incluídos os cabos coaxiais) e ou...",Camaçari,Polônia
8581658,2026,1,81,SC,4205407,15261,76679,6110,"Camisolas e pulôveres, cardigans, coletes e ar...",Florianópolis,Bangladesh
8581659,2026,1,351,SP,3425904,419,6861,6601,"Guarda-chuvas, sombrinhas e guarda-sóis (inclu...",Jundiaí,Hong Kong

In [ ]:
print(impfinal.columns)

Index(['CO_ANO', 'CO_MES', 'CO_PAIS', 'SG_UF_MUN', 'CO_MUN', 'TOTAL KGL IMP.',
       'TOTAL IMPORTADO', 'CO_SH4', 'NO_SH4_POR', 'NO_MUN_MIN', 'NO_PAIS'],
      dtype='object')

In [ ]:
impfinal.to_csv(origem+'dado_imp_final.csv',index=False)