<a href="https://colab.research.google.com/github/JoseSergio414/Projeto-Integrador-II/blob/main/PROJETOII_dados_finais_expfinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cadeia Automotiva dados finais exportação

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
origem = '/content/drive/MyDrive/Data/COMEXSTAT/'

In [ ]:
arquivo_1 = origem + 'dado_exp_final.csv'

In [ ]:
expfinal = pd.read_csv(arquivo_1,low_memory=False,sep=',',encoding='UTF-8')

In [ ]:
expfinal = expfinal.rename(columns={'TOTAL IMPORTADO': 'TOTAL EXPORTADO'})

In [ ]:
expfinal = expfinal.rename(columns={'KG_LIQUIDO': 'TOTAL KGL EXP.'})

In [ ]:
expfinal.head(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,TOTAL KGL EXP.,TOTAL EXPORTADO,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
0,2021,3,493,SP,3434401,966,7788,3305,Preparações capilares,Osasco,México
1,2021,7,386,SP,3409502,1,1544,8419,"Aparelhos e dispositivos, mesmo aquecidos elec...",Campinas,Itália
2,2021,12,63,PR,4106902,73,907,8511,Aparelhos e dispositivos elétricos de ignição ...,Curitiba,Argentina
3,2021,7,586,SC,4202909,75,3942,6204,"Fatos de saia-casaco, conjuntos, casacos, vest...",Brusque,Paraguai
4,2021,8,63,SP,3440002,6949,29604,8708,Partes e acessórios dos veículos automóveis da...,Pompéia,Argentina

In [ ]:
expfinal.head()

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,TOTAL KGL EXP.,TOTAL EXPORTADO,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
0,2021,3,493,SP,3434401,966,7788,3305,Preparações capilares,Osasco,México
1,2021,7,386,SP,3409502,1,1544,8419,"Aparelhos e dispositivos, mesmo aquecidos elec...",Campinas,Itália
2,2021,12,63,PR,4106902,73,907,8511,Aparelhos e dispositivos elétricos de ignição ...,Curitiba,Argentina
3,2021,7,586,SC,4202909,75,3942,6204,"Fatos de saia-casaco, conjuntos, casacos, vest...",Brusque,Paraguai
4,2021,8,63,SP,3440002,6949,29604,8708,Partes e acessórios dos veículos automóveis da...,Pompéia,Argentina

In [ ]:
expfinal.tail(5)

,CO_ANO,CO_MES,CO_PAIS,SG_UF_MUN,CO_MUN,TOTAL KGL EXP.,TOTAL EXPORTADO,CO_SH4,NO_SH4_POR,NO_MUN_MIN,NO_PAIS
5811674,2026,2,63,SP,3430607,35,4944,2849,Carbonetos de constituição química definida ou...,Mogi das Cruzes,Argentina
5811675,2026,1,361,RS,4316808,518,41461,4813,"Papel para cigarros, mesmo cortado nas dimensõ...",Santa Cruz do Sul,Índia
5811676,2026,1,63,RS,4302105,266,533,1902,"Massas alimentícias, mesmo cozidas ou recheada...",Bento Gonçalves,Argentina
5811677,2026,1,741,RJ,3304524,8,627,8907,Outras estruturas flutuantes (por exemplo: bal...,Rio das Ostras,Singapura
5811678,2026,2,580,RS,4309308,0,73,8541,"Díodos, transístores e dispositivos semelhante...",Guaíba,Panamá

In [ ]:
print(expfinal.columns)

Index(['CO_ANO', 'CO_MES', 'CO_PAIS', 'SG_UF_MUN', 'CO_MUN', 'TOTAL KGL EXP.',
       'TOTAL EXPORTADO', 'CO_SH4', 'NO_SH4_POR', 'NO_MUN_MIN', 'NO_PAIS'],
      dtype='object')

In [ ]:
expfinal.to_csv(origem+'dado_exp_final.csv',index=False)